SELECT T0.*,
  T1.AFF_LIST
FROM
  (SELECT SRC,
    LISTAGG(CNTRY_ID, ', ') WITHIN GROUP(
  ORDER BY AFF_ID) AS CNTRY_LIST
  FROM
    (SELECT CNTRY_ID,
      AFF_ID,
      MAX(NEW_SYSTEM_NM) KEEP(DENSE_RANK LAST
    ORDER BY LAUNCH_MO_YR_ID) AS SRC
    FROM
      (SELECT CNTRY_ID,
        AFF_ID,
        LAUNCH_MO_YR_ID,
        NEW_SYSTEM_NM,
        DENSE_RANK(202104) WITHIN GROUP(
      ORDER BY LAUNCH_MO_YR_ID DESC) AS FOCUS_MO_YR_RNK
      FROM SOURCES_EIA T0
      GROUP BY CNTRY_ID,
        AFF_ID,
        LAUNCH_MO_YR_ID,
        NEW_SYSTEM_NM
      )
    WHERE FOCUS_MO_YR_RNK=1
    GROUP BY CNTRY_ID,
      AFF_ID
    )
  GROUP BY SRC
  ) T0
LEFT JOIN
  (SELECT SRC,
    LISTAGG(AFF_ID, ', ') WITHIN GROUP(
  ORDER BY AFF_ID) AS AFF_LIST
  FROM
    (SELECT AFF_ID,
      MAX(NEW_SYSTEM_NM) KEEP(DENSE_RANK LAST
    ORDER BY LAUNCH_MO_YR_ID) AS SRC
    FROM
      (SELECT AFF_ID,
        LAUNCH_MO_YR_ID,
        NEW_SYSTEM_NM,
        DENSE_RANK(202104) WITHIN GROUP(
      ORDER BY LAUNCH_MO_YR_ID DESC) AS FOCUS_MO_YR_RNK
      FROM SOURCES_EIA T0
      GROUP BY AFF_ID,
        LAUNCH_MO_YR_ID,
        NEW_SYSTEM_NM
      )
    WHERE FOCUS_MO_YR_RNK=1
    GROUP BY AFF_ID
    )
  GROUP BY SRC
  ) T1
ON T0.SRC=T1.SRC
