CREATE TABLE DWSEAI01.DS_DET_DAILY_PM_STG
(
 OPER_AFF_ID NUMBER(38,0),
OPER_CNTRY_ID NUMBER(38,0),
SHP_CNTRY_ID NUMBER(38,0),
ORD_DT TIMESTAMP(6),
ORD_DT_KEY_NO NUMBER(8,0),
ORD_MO_YR_ID NUMBER(6,0),
SHP_DT TIMESTAMP(6),
SHP_DT_KEY_NO NUMBER(8,0),
SHP_MO_YR_ID NUMBER(6,0),
COMB_ORD_FLAG VARCHAR2(5 BYTE),
COMB_ORD_ID NUMBER(38,0),
ORD_ID NUMBER(38,0),
INV_CD VARCHAR2(240 CHAR),
CURCY_CD VARCHAR2(3 CHAR),
ORD_CHANNEL VARCHAR2(240 CHAR),
WHSE_CD VARCHAR2(240 CHAR),
ORD_WHSE_CD VARCHAR2(240 CHAR),
SHP_POSTAL_CD VARCHAR2(240 CHAR),
ACCOUNT_ID NUMBER,
ACCOUNT_TYPE_ORD VARCHAR2(8 BYTE),
VOL_ACCOUNT_ID NUMBER(38,0),
ORD_ACCOUNT_ID NUMBER(38,0),
SHP_ACCOUNT_ID NUMBER(38,0),
ORD_CANC_FLAG VARCHAR2(5 BYTE),
ORD_SHP_FLAG VARCHAR2(5 BYTE),
PAY_REQ_FLAG VARCHAR2(5 BYTE),
ORD_PAID_FLAG VARCHAR2(5 BYTE),
ORG_ORD_ID NUMBER,
ORD_TYPE_CD VARCHAR2(240 CHAR),
DROP_CD VARCHAR2(240 CHAR),
DELIVERY_FEE_NET NUMBER,
ORD_LN_ID NUMBER(38,0),
REF_LN_ID NUMBER(38,0),
ORD_LN_DISP_CD VARCHAR2(240 CHAR),
ORD_ITEM_CD VARCHAR2(960 BYTE),
SHP_ITEM_CD VARCHAR2(240 CHAR),
ORD_ITEM_BASE_CD VARCHAR2(15 CHAR),
SHP_ITEM_BASE_CD VARCHAR2(15 CHAR),
ADJ_LN_LC_NET NUMBER,
ADJ_LN_PV NUMBER,
ADJ_LN_BV NUMBER,
ORD_QTY NUMBER,
SHP_QTY NUMBER,
DELIVERY_MODE_CD VARCHAR2(240 CHAR),
CONSULTANT_CD VARCHAR2(50 CHAR),
UPDATE_DT TIMESTAMP(6)
) 
NOLOGGING 
TABLESPACE DWREAI01 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
PARALLEL 8 
PARTITION BY LIST (OPER_CNTRY_ID) 
  (
    PARTITION DS_DET_DAILY_PM_AFF_10 VALUES (10, 20, 580, 700) TABLESPACE DWREAI01 
  PCTFREE 0 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  COMPRESS FOR QUERY HIGH 
  , PARTITION DS_DET_DAILY_PM_AFF_30 VALUES (30, 240) TABLESPACE DWREAI01 
  PCTFREE 0 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  COMPRESS FOR QUERY HIGH 
  , PARTITION DS_DET_DAILY_PM_AFF_40 VALUES (40, 300) TABLESPACE DWREAI01 
  PCTFREE 0 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  COMPRESS FOR QUERY HIGH 
  , PARTITION DS_DET_DAILY_PM_AFF_60 VALUES (60, 80) TABLESPACE DWREAI01 
  PCTFREE 0 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  COMPRESS FOR QUERY HIGH 
  , PARTITION DS_DET_DAILY_PM_AFF_70 VALUES (70) TABLESPACE DWREAI01 
  PCTFREE 0 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  COMPRESS FOR QUERY HIGH 
  , PARTITION DS_DET_DAILY_PM_AFF_90 VALUES (90, 120) TABLESPACE DWREAI01 
  PCTFREE 0 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  COMPRESS FOR QUERY HIGH 
  , PARTITION DS_DET_DAILY_PM_AFF_100 VALUES (100, 530, 780) TABLESPACE DWREAI01 
  PCTFREE 0 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  COMPRESS FOR QUERY HIGH  
  , PARTITION DS_DET_DAILY_PM_AFF_110 VALUES (110) TABLESPACE DWREAI01 
  PCTFREE 0 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  COMPRESS FOR QUERY HIGH 
  , PARTITION DS_DET_DAILY_PM_AFF_130 VALUES (130) TABLESPACE DWREAI01 
  PCTFREE 0 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  COMPRESS FOR QUERY HIGH 
  , PARTITION DS_DET_DAILY_PM_AFF_150 VALUES (140, 150, 340, 390, 450, 490, 590, 620, 650, 660, 800, 810, 820) TABLESPACE DWREAI01 
  PCTFREE 0 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  COMPRESS FOR QUERY HIGH  
  , PARTITION DS_DET_DAILY_PM_AFF_160 VALUES (160) TABLESPACE DWREAI01 
  PCTFREE 0 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  COMPRESS FOR QUERY HIGH 
  , PARTITION DS_DET_DAILY_PM_AFF_170 VALUES (170, 190, 230, 260, 290, 310, 380, 400, 440, 510, 520, 600) TABLESPACE DWREAI01 
  PCTFREE 0 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  COMPRESS FOR QUERY HIGH   
  , PARTITION DS_DET_DAILY_PM_AFF_180 VALUES (180) TABLESPACE DWREAI01 
  PCTFREE 0 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  COMPRESS FOR QUERY HIGH  
  , PARTITION DS_DET_DAILY_PM_AFF_200 VALUES (200) TABLESPACE DWREAI01 
  PCTFREE 0 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  COMPRESS FOR QUERY HIGH 
  , PARTITION DS_DET_DAILY_PM_AFF_210 VALUES (210) TABLESPACE DWREAI01 
  PCTFREE 0 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  COMPRESS FOR QUERY HIGH 
  , PARTITION DS_DET_DAILY_PM_AFF_220 VALUES (220) TABLESPACE DWREAI01 
  PCTFREE 0 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  COMPRESS FOR QUERY HIGH 
  , PARTITION DS_DET_DAILY_PM_AFF_250 VALUES (250, 270) TABLESPACE DWREAI01 
  PCTFREE 0 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  COMPRESS FOR QUERY HIGH 
  , PARTITION DS_DET_DAILY_PM_AFF_350 VALUES (350) TABLESPACE DWREAI01 
  PCTFREE 0 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  COMPRESS FOR QUERY HIGH 
  , PARTITION DS_DET_DAILY_PM_AFF_360 VALUES (50, 360) TABLESPACE DWREAI01 
  PCTFREE 0 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  COMPRESS FOR QUERY HIGH  
  , PARTITION DS_DET_DAILY_PM_AFF_420 VALUES (420, 830) TABLESPACE DWREAI01 
  PCTFREE 0 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  COMPRESS FOR QUERY HIGH 
  , PARTITION DS_DET_DAILY_PM_AFF_430 VALUES (430) TABLESPACE DWREAI01 
  PCTFREE 0 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  COMPRESS FOR QUERY HIGH 
  , PARTITION DS_DET_DAILY_PM_AFF_470 VALUES (280, 370, 460, 470) TABLESPACE DWREAI01 
  PCTFREE 0 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  COMPRESS FOR QUERY HIGH 
  , PARTITION DS_DET_DAILY_PM_AFF_480 VALUES (480) TABLESPACE DWREAI01 
  PCTFREE 0 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  COMPRESS FOR QUERY HIGH 
  , PARTITION DS_DET_DAILY_PM_AFF_570 VALUES (570, 740, 750) TABLESPACE DWREAI01 
  PCTFREE 0 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  COMPRESS FOR QUERY HIGH 
  , PARTITION DS_DET_DAILY_PM_AFF_500 VALUES (500) TABLESPACE DWREAI01 
  PCTFREE 0 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  COMPRESS FOR QUERY HIGH  
  , PARTITION DS_DET_DAILY_PM_OTHR VALUES (DEFAULT) TABLESPACE DWREAI01 
  PCTFREE 0 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  COMPRESS FOR QUERY HIGH 
  )
