CREATE MATERIALIZED VIEW DS_PEND_M_SRC ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "DWREAI01" BUILD IMMEDIATE USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "DWREAI01" REFRESH COMPLETE ON DEMAND USING DEFAULT LOCAL ROLLBACK SEGMENT USING ENFORCED CONSTRAINTS ENABLE QUERY REWRITE
                                                                                                                   AS
  SELECT COALESCE(EU_AS400, 0)                                                                                     AS EU_AS400,
    COALESCE(EU_ATLAS, 0)                                                                                          AS EU_ATLAS,
    COALESCE(EU_HYBR_EOM, 0)                                                                                       AS EU_HYBR_EOM,
    COALESCE(EU_HYBR_NON_EOM, 0)                                                                                   AS EU_HYBR_NON_EOM,
    GREATEST(COALESCE(EU_AS400, 0), COALESCE(EU_ATLAS, 0), COALESCE(EU_HYBR_EOM, 0), COALESCE(EU_HYBR_NON_EOM, 0)) AS ORD_MO_YR_ID,
    UPDT_ON_LAST_RUN_FLG,
    DENSE_RANK() OVER(ORDER BY GREATEST(COALESCE(EU_AS400, 0), COALESCE(EU_ATLAS, 0), COALESCE(EU_HYBR_EOM, 0), COALESCE(EU_HYBR_NON_EOM, 0)) DESC) AS MNTH_RNK
  FROM
    (SELECT *
    FROM
      (SELECT SRC,
        ORD_MO_YR_ID,
        UPDT_ON_LAST_RUN_FLG,
        DENSE_RANK() OVER(ORDER BY ORD_MO_YR_ID DESC)             AS MNTH_RNK
      FROM DWSEAI01.DS_PENDING_MONTHS
      )
    WHERE UPDT_ON_LAST_RUN_FLG         =0
    OR MNTH_RNK                       <=2
    ) PIVOT(MAX(ORD_MO_YR_ID) FOR SRC IN ('EU_AS400' AS EU_AS400, 'EU_ATLAS' AS EU_ATLAS, 'EU_HYBR_EOM' AS EU_HYBR_EOM, 'EU_HYBR_NON_EOM' AS EU_HYBR_NON_EOM))
