DECLARE
  LAST_YM_VAR INTEGER:=0;
BEGIN
  SELECT MAX(CAST(SUBSTR(PARTITION_NAME, -6) AS INTEGER))
  INTO LAST_YM_VAR
  FROM ALL_TAB_PARTITIONS
  WHERE TABLE_OWNER='DWSEAI01'
  AND TABLE_NAME   ='MRMS_INVOICES';
  IF {YEARMONTH}   >LAST_YM_VAR THEN
    EXECUTE IMMEDIATE
    'ALTER TABLE DWSEAI01.MRMS_INVOICES ADD PARTITION MRMS_INVOICES_{YEARMONTH} VALUES ({YEARMONTH})   
LOGGING   
TABLESPACE DWREAI01   
PCTFREE 0   
INITRANS 1   
STORAGE   
(     
BUFFER_POOL DEFAULT   
)   
COMPRESS FOR QUERY HIGH   
(    
SUBPARTITION MRMS_INVOICES_{YEARMONTH}_AFF_10 VALUES (10, 20, 580, 700) TABLESPACE DWREAI01     
COMPRESS FOR QUERY HIGH    
, SUBPARTITION MRMS_INVOICES_{YEARMONTH}_AFF_30 VALUES (30, 240) TABLESPACE DWREAI01     
COMPRESS FOR QUERY HIGH    
, SUBPARTITION MRMS_INVOICES_{YEARMONTH}_AFF_40 VALUES (40, 300) TABLESPACE DWREAI01     
COMPRESS FOR QUERY HIGH    
, SUBPARTITION MRMS_INVOICES_{YEARMONTH}_AFF_60 VALUES (60, 80) TABLESPACE DWREAI01     
COMPRESS FOR QUERY HIGH    
, SUBPARTITION MRMS_INVOICES_{YEARMONTH}_AFF_70 VALUES (70) TABLESPACE DWREAI01     
COMPRESS FOR QUERY HIGH    
, SUBPARTITION MRMS_INVOICES_{YEARMONTH}_AFF_90 VALUES (90, 120) TABLESPACE DWREAI01     
COMPRESS FOR QUERY HIGH    
, SUBPARTITION MRMS_INVOICES_{YEARMONTH}_AFF_100 VALUES (100, 530, 780) TABLESPACE DWREAI01     
COMPRESS FOR QUERY HIGH    
, SUBPARTITION MRMS_INVOICES_{YEARMONTH}_AFF_110 VALUES (110) TABLESPACE DWREAI01     
COMPRESS FOR QUERY HIGH    
, SUBPARTITION MRMS_INVOICES_{YEARMONTH}_AFF_130 VALUES (130) TABLESPACE DWREAI01     
COMPRESS FOR QUERY HIGH    
, SUBPARTITION MRMS_INVOICES_{YEARMONTH}_AFF_150 VALUES (140, 150, 340, 390, 450, 490, 590, 620, 650, 660, 800, 810, 820) TABLESPACE DWREAI01     
COMPRESS FOR QUERY HIGH    
, SUBPARTITION MRMS_INVOICES_{YEARMONTH}_AFF_160 VALUES (160) TABLESPACE DWREAI01     
COMPRESS FOR QUERY HIGH    
, SUBPARTITION MRMS_INVOICES_{YEARMONTH}_AFF_170 VALUES (170, 190, 230, 260, 290, 310, 380, 400, 440, 510, 520, 600) TABLESPACE DWREAI01     
COMPRESS FOR QUERY HIGH    
, SUBPARTITION MRMS_INVOICES_{YEARMONTH}_AFF_180 VALUES (180) TABLESPACE DWREAI01     
COMPRESS FOR QUERY HIGH    
, SUBPARTITION MRMS_INVOICES_{YEARMONTH}_AFF_200 VALUES (200) TABLESPACE DWREAI01     
COMPRESS FOR QUERY HIGH    
, SUBPARTITION MRMS_INVOICES_{YEARMONTH}_AFF_210 VALUES (210) TABLESPACE DWREAI01     
COMPRESS FOR QUERY HIGH    
, SUBPARTITION MRMS_INVOICES_{YEARMONTH}_AFF_220 VALUES (220) TABLESPACE DWREAI01     
COMPRESS FOR QUERY HIGH    
, SUBPARTITION MRMS_INVOICES_{YEARMONTH}_AFF_250 VALUES (250, 270) TABLESPACE DWREAI01     
COMPRESS FOR QUERY HIGH    
, SUBPARTITION MRMS_INVOICES_{YEARMONTH}_AFF_350 VALUES (350) TABLESPACE DWREAI01     
COMPRESS FOR QUERY HIGH    
, SUBPARTITION MRMS_INVOICES_{YEARMONTH}_AFF_360 VALUES (50, 360) TABLESPACE DWREAI01     
COMPRESS FOR QUERY HIGH    
, SUBPARTITION MRMS_INVOICES_{YEARMONTH}_AFF_420 VALUES (420, 830) TABLESPACE DWREAI01     
COMPRESS FOR QUERY HIGH    
, SUBPARTITION MRMS_INVOICES_{YEARMONTH}_AFF_430 VALUES (430) TABLESPACE DWREAI01     
COMPRESS FOR QUERY HIGH    
, SUBPARTITION MRMS_INVOICES_{YEARMONTH}_AFF_470 VALUES (280, 370, 460, 470) TABLESPACE DWREAI01     
COMPRESS FOR QUERY HIGH    
, SUBPARTITION MRMS_INVOICES_{YEARMONTH}_AFF_480 VALUES (480) TABLESPACE DWREAI01     
COMPRESS FOR QUERY HIGH    
, SUBPARTITION MRMS_INVOICES_{YEARMONTH}_AFF_570 VALUES (570, 740, 750) TABLESPACE DWREAI01     
COMPRESS FOR QUERY HIGH    
, SUBPARTITION MRMS_INVOICES_{YEARMONTH}_AFF_500 VALUES (500) TABLESPACE DWREAI01     
COMPRESS FOR QUERY HIGH    
, SUBPARTITION MRMS_INVOICES_{YEARMONTH}_OTHR VALUES (DEFAULT) TABLESPACE DWREAI01     
COMPRESS FOR QUERY HIGH    
)'
    ;
  END IF;
END;
