CREATE TABLE DWSEAI01.MRMS_INVOICES_STG
(
  AFF_ID NUMBER(38, 0) 
, TRX_SOURC_CD VARCHAR2(3 CHAR) 
, CNTRY_ID NUMBER(38, 0) 
, ORG_ORD_ID NUMBER 
, ORD_DT TIMESTAMP(6) 
, ATM_UPDATE_DT TIMESTAMP(6) 
, ORD_BUS_NATR_CD VARCHAR2(3 CHAR) 
, VOL_ACCOUNT_ID NUMBER(38, 0) 
, INVOICE_CD VARCHAR2(240 CHAR) 
, ORD_MO_YR_ID NUMBER(6, 0) 
) 
NOLOGGING 
TABLESPACE DWREAI01 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
PARALLEL 8 
PARTITION BY LIST (CNTRY_ID) 
  (
    PARTITION MRMS_INVOICES_STG_10 VALUES (10, 20, 580, 700) TABLESPACE DWREAI01 
  PCTFREE 0 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  COMPRESS FOR QUERY HIGH 
  , PARTITION MRMS_INVOICES_STG_30 VALUES (30, 240) TABLESPACE DWREAI01 
  PCTFREE 0 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  COMPRESS FOR QUERY HIGH 
  , PARTITION MRMS_INVOICES_STG_40 VALUES (40, 300) TABLESPACE DWREAI01 
  PCTFREE 0 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  COMPRESS FOR QUERY HIGH 
  , PARTITION MRMS_INVOICES_STG_60 VALUES (60, 80) TABLESPACE DWREAI01 
  PCTFREE 0 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  COMPRESS FOR QUERY HIGH 
  , PARTITION MRMS_INVOICES_STG_70 VALUES (70) TABLESPACE DWREAI01 
  PCTFREE 0 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  COMPRESS FOR QUERY HIGH 
  , PARTITION MRMS_INVOICES_STG_90 VALUES (90, 120) TABLESPACE DWREAI01 
  PCTFREE 0 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  COMPRESS FOR QUERY HIGH 
  , PARTITION MRMS_INVOICES_STG_100 VALUES (100, 530, 780) TABLESPACE DWREAI01 
  PCTFREE 0 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  COMPRESS FOR QUERY HIGH  
  , PARTITION MRMS_INVOICES_STG_110 VALUES (110) TABLESPACE DWREAI01 
  PCTFREE 0 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  COMPRESS FOR QUERY HIGH 
  , PARTITION MRMS_INVOICES_STG_130 VALUES (130) TABLESPACE DWREAI01 
  PCTFREE 0 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  COMPRESS FOR QUERY HIGH 
  , PARTITION MRMS_INVOICES_STG_150 VALUES (140, 150, 340, 390, 450, 490, 590, 620, 650, 660, 800, 810, 820) TABLESPACE DWREAI01 
  PCTFREE 0 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  COMPRESS FOR QUERY HIGH  
  , PARTITION MRMS_INVOICES_STG_160 VALUES (160) TABLESPACE DWREAI01 
  PCTFREE 0 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  COMPRESS FOR QUERY HIGH 
  , PARTITION MRMS_INVOICES_STG_170 VALUES (170, 190, 230, 260, 290, 310, 380, 400, 440, 510, 520, 600) TABLESPACE DWREAI01 
  PCTFREE 0 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  COMPRESS FOR QUERY HIGH   
  , PARTITION MRMS_INVOICES_STG_180 VALUES (180) TABLESPACE DWREAI01 
  PCTFREE 0 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  COMPRESS FOR QUERY HIGH  
  , PARTITION MRMS_INVOICES_STG_200 VALUES (200) TABLESPACE DWREAI01 
  PCTFREE 0 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  COMPRESS FOR QUERY HIGH 
  , PARTITION MRMS_INVOICES_STG_210 VALUES (210) TABLESPACE DWREAI01 
  PCTFREE 0 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  COMPRESS FOR QUERY HIGH 
  , PARTITION MRMS_INVOICES_STG_220 VALUES (220) TABLESPACE DWREAI01 
  PCTFREE 0 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  COMPRESS FOR QUERY HIGH 
  , PARTITION MRMS_INVOICES_STG_250 VALUES (250, 270) TABLESPACE DWREAI01 
  PCTFREE 0 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  COMPRESS FOR QUERY HIGH 
  , PARTITION MRMS_INVOICES_STG_350 VALUES (350) TABLESPACE DWREAI01 
  PCTFREE 0 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  COMPRESS FOR QUERY HIGH 
  , PARTITION MRMS_INVOICES_STG_360 VALUES (50, 360) TABLESPACE DWREAI01 
  PCTFREE 0 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  COMPRESS FOR QUERY HIGH  
  , PARTITION MRMS_INVOICES_STG_420 VALUES (420, 830) TABLESPACE DWREAI01 
  PCTFREE 0 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  COMPRESS FOR QUERY HIGH 
  , PARTITION MRMS_INVOICES_STG_430 VALUES (430) TABLESPACE DWREAI01 
  PCTFREE 0 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  COMPRESS FOR QUERY HIGH 
  , PARTITION MRMS_INVOICES_STG_470 VALUES (280, 370, 460, 470) TABLESPACE DWREAI01 
  PCTFREE 0 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  COMPRESS FOR QUERY HIGH 
  , PARTITION MRMS_INVOICES_STG_480 VALUES (480) TABLESPACE DWREAI01 
  PCTFREE 0 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  COMPRESS FOR QUERY HIGH 
  , PARTITION MRMS_INVOICES_STG_570 VALUES (570, 740, 750) TABLESPACE DWREAI01 
  PCTFREE 0 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  COMPRESS FOR QUERY HIGH 
  , PARTITION MRMS_INVOICES_STG_500 VALUES (500) TABLESPACE DWREAI01 
  PCTFREE 0 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  COMPRESS FOR QUERY HIGH  
  , PARTITION DS_DET_DAILY_PM_OTHR VALUES (DEFAULT) TABLESPACE DWREAI01 
  PCTFREE 0 
  INITRANS 1 
  STORAGE 
  ( 
    BUFFER_POOL DEFAULT 
  ) 
  COMPRESS FOR QUERY HIGH 
  )
