SELECT DISTINCT T1.AFF_NO AS AFF_ID,
  T1.TRX_SOURC_CD,
  T1.BUS_ENTTY_NO                                          AS CNTRY_ID,
  COALESCE(MIN(CAST(T1.ORGNL_ORD_NO AS NUMBER)),0)         AS ORG_ORD_ID,
  T1.ORD_DT                                                AS ORD_DT,
  CAST(SYSDATE AS TIMESTAMP(6))                            AS ATM_UPDATE_DT,
  COALESCE(MIN(TRIM(T1.ORD_BUS_NATR_CD)),'1')              AS ORD_BUS_NATR_CD,
  CAST(T2.IBO_NO AS        NUMBER)                         AS VOL_ACCOUNT_ID,
  CAST(T1.ORGNL_REF_TXT AS VARCHAR2(240 CHAR))             AS INVOICE_CD,
  EXTRACT(YEAR FROM ORD_DT)*100+EXTRACT(MONTH FROM ORD_DT) AS ORD_MO_YR_ID
FROM
 (SELECT *
  FROM
    (SELECT T0.*,
      DENSE_RANK() OVER(PARTITION BY BUS_ENTTY_NO, ORGNL_REF_TXT, BNS_CUST_ID ORDER BY ORD_DT ASC) AS TRX_RANK
    FROM WWSMGC01.WWT03900_TRX_MST T0
    WHERE AFF_NO          IN (570, 30)
    AND TRIM (TRX_SOURC_CD)='003'
    AND EXTRACT(YEAR FROM ORD_DT)*100+EXTRACT(MONTH FROM ORD_DT)={FOCUS_YM}
    )
  WHERE TRX_RANK=1
  ) T1                    
LEFT JOIN
  (SELECT * FROM WWSEBS01.WWT01010_BNS_CUST_MST WHERE AFF_NO IN (570, 30)
  ) T2
ON T1.BNS_CUST_ID         = T2.BNS_CUST_ID
WHERE T1.ORGNL_REF_TXT   IS NOT NULL
GROUP BY T1.AFF_NO,
  T1.TRX_SOURC_CD,
  T1.BUS_ENTTY_NO,
  T1.ORD_DT,
  CAST(T2.IBO_NO AS        NUMBER),
  CAST(T1.ORGNL_REF_TXT AS VARCHAR2(240 CHAR)),
  EXTRACT(YEAR FROM ORD_DT)*100+EXTRACT(MONTH FROM ORD_DT)
