SELECT DISTINCT EXTRACT(YEAR FROM ORD_DT)*100+EXTRACT(MONTH FROM ORD_DT) AS ORD_MO_YR_ID
  FROM WWSMGC01.WWT03900_TRX_MST
  WHERE AFF_NO                IN (570, 30, 430, 250)
  AND TRIM (TRX_SOURC_CD)='003'
  AND EXTRACT(YEAR FROM GREATEST(TRX_CREAT_DTM, AUDIT_CREAT_DTM,AUDIT_CHNG_DTM))*10000+
EXTRACT(MONTH FROM GREATEST(TRX_CREAT_DTM, AUDIT_CREAT_DTM,AUDIT_CHNG_DTM))*100+
EXTRACT(DAY FROM GREATEST(TRX_CREAT_DTM, AUDIT_CREAT_DTM,AUDIT_CHNG_DTM))={SYS_YM}
